package com.vaibhavjoshi.quizapp.db

import android.content.Context
import android.database.sqlite.SQLiteDatabase
import android.database.sqlite.SQLiteOpenHelper
import com.vaibhavjoshi.quizapp.R

class QuizDatabaseHelper(context: Context) : SQLiteOpenHelper(context, DATABASE_NAME, null, DATABASE_VERSION) {

    // Define the table and columns
    companion object {
        private const val DATABASE_NAME = "quiz.db"
        private const val DATABASE_VERSION = 1

        const val TABLE_NAME        = "questions"
        const val COLUMN_ID         = "id"
        const val COLUMN_QUESTION   = "question"
        const val COLUMN_OPTION1    = "option1"
        const val COLUMN_OPTION2    = "option2"
        const val COLUMN_OPTION3    = "option3"
        const val COLUMN_OPTION4    = "option4"
        const val COLUMN_ANSWER     = "answer"
    }

    // Create the questions table
    override fun onCreate(db: SQLiteDatabase) {
        val createTable = ("CREATE TABLE $TABLE_NAME ("
                + "$COLUMN_ID INTEGER PRIMARY KEY AUTOINCREMENT,"
                + "$COLUMN_QUESTION TEXT,"
                + "$COLUMN_OPTION1 TEXT,"
                + "$COLUMN_OPTION2 TEXT,"
                + "$COLUMN_OPTION3 TEXT,"
                + "$COLUMN_OPTION4 TEXT,"
                + "$COLUMN_ANSWER TEXT)"
                )
        db.execSQL(createTable)
        populateQuestions(db)
    }

    // Update the database schema if needed
    override fun onUpgrade(db: SQLiteDatabase, oldVersion: Int, newVersion: Int) {
        db.execSQL("DROP TABLE IF EXISTS $TABLE_NAME")
        onCreate(db)
    }

    // Populate the questions table with data
    private fun populateQuestions(db: SQLiteDatabase) {
        val questions = arrayOf(
            "INSERT INTO $TABLE_NAME ($COLUMN_QUESTION, $COLUMN_OPTION1, $COLUMN_OPTION2, $COLUMN_OPTION3, $COLUMN_OPTION4, $COLUMN_ANSWER) VALUES ('Who is the Prime Minister of India?'                           , 'Narendra Modi'           , 'Rahul Gandhi'    , 'Manmohan Singh'      , 'Amit Shah'           , 'Narendra Modi'           )",
            "INSERT INTO $TABLE_NAME ($COLUMN_QUESTION, $COLUMN_OPTION1, $COLUMN_OPTION2, $COLUMN_OPTION3, $COLUMN_OPTION4, $COLUMN_ANSWER) VALUES ('What is the capital of India?'                                 , 'Mumbai'                  , 'Chennai'         , 'Delhi'               , 'Ahmedabad'           , 'Delhi'                   )",
            "INSERT INTO $TABLE_NAME ($COLUMN_QUESTION, $COLUMN_OPTION1, $COLUMN_OPTION2, $COLUMN_OPTION3, $COLUMN_OPTION4, $COLUMN_ANSWER) VALUES ('What is sum of 15 + 25?'                                       , '5'                       , '25'              , '40'                  , 'None'                , '40'                      )",
            "INSERT INTO $TABLE_NAME ($COLUMN_QUESTION, $COLUMN_OPTION1, $COLUMN_OPTION2, $COLUMN_OPTION3, $COLUMN_OPTION4, $COLUMN_ANSWER) VALUES ('Which one is maximum? 25, 11, 17, 18, 40, 42'                  , '11'                      , '42'              , '17'                  , 'None'                , '42'                      )",
            "INSERT INTO $TABLE_NAME ($COLUMN_QUESTION, $COLUMN_OPTION1, $COLUMN_OPTION2, $COLUMN_OPTION3, $COLUMN_OPTION4, $COLUMN_ANSWER) VALUES ('What is the official language of Gujarat?'                     , 'Hindi'                   , 'Gujarati'        , 'Marathi'             , 'None'                , 'Gujarati'                )",
            "INSERT INTO $TABLE_NAME ($COLUMN_QUESTION, $COLUMN_OPTION1, $COLUMN_OPTION2, $COLUMN_OPTION3, $COLUMN_OPTION4, $COLUMN_ANSWER) VALUES ('What is multiplication of 12 * 12 ?'                           , '124'                     , '12'              , '24'                  , 'None'                , 'None'                    )",
            "INSERT INTO $TABLE_NAME ($COLUMN_QUESTION, $COLUMN_OPTION1, $COLUMN_OPTION2, $COLUMN_OPTION3, $COLUMN_OPTION4, $COLUMN_ANSWER) VALUES ('Which state of India has the largest population?'              , 'UP'                      , 'Bihar'           , 'Gujarat'             , 'Maharashtra'         , 'UP'                      )",
            "INSERT INTO $TABLE_NAME ($COLUMN_QUESTION, $COLUMN_OPTION1, $COLUMN_OPTION2, $COLUMN_OPTION3, $COLUMN_OPTION4, $COLUMN_ANSWER) VALUES ('Who is the Home Minister of India?'                            , 'Amit Shah'               , 'Rajnath Singh'   , 'Narendra Modi'       , 'None'                , 'Amit Shah'               )",
            "INSERT INTO $TABLE_NAME ($COLUMN_QUESTION, $COLUMN_OPTION1, $COLUMN_OPTION2, $COLUMN_OPTION3, $COLUMN_OPTION4, $COLUMN_ANSWER) VALUES ('What is the capital of Gujarat?'                               , 'Vadodara'                , 'Ahmedabad'       , 'Gandhinagar'         , 'Rajkot'              , 'Gandhinagar'             )",
            "INSERT INTO $TABLE_NAME ($COLUMN_QUESTION, $COLUMN_OPTION1, $COLUMN_OPTION2, $COLUMN_OPTION3, $COLUMN_OPTION4, $COLUMN_ANSWER) VALUES ('Which number will be next in series? 1, 4, 9, 16, 25'          , '21'                      , '36'              , '49'                  , '32'                  , '36'                      )",
            "INSERT INTO $TABLE_NAME ($COLUMN_QUESTION, $COLUMN_OPTION1, $COLUMN_OPTION2, $COLUMN_OPTION3, $COLUMN_OPTION4, $COLUMN_ANSWER) VALUES ('Which one is minimum? 5, 0, -20, 11'                           , '0'                       , '11'              , '-20'                 , 'None'                , '-20'                     )",
            "INSERT INTO $TABLE_NAME ($COLUMN_QUESTION, $COLUMN_OPTION1, $COLUMN_OPTION2, $COLUMN_OPTION3, $COLUMN_OPTION4, $COLUMN_ANSWER) VALUES ('What is sum of 10, 12 and 15?'                                 , '37'                      , '25'              , '10'                  , '12'                  , '37'                      )",
            "INSERT INTO $TABLE_NAME ($COLUMN_QUESTION, $COLUMN_OPTION1, $COLUMN_OPTION2, $COLUMN_OPTION3, $COLUMN_OPTION4, $COLUMN_ANSWER) VALUES ('What is the official language of the Government of India?'     , 'Hindi'                   , 'English'         , 'Gujarati'            , 'None'                , 'Hindi'                   )",
            "INSERT INTO $TABLE_NAME ($COLUMN_QUESTION, $COLUMN_OPTION1, $COLUMN_OPTION2, $COLUMN_OPTION3, $COLUMN_OPTION4, $COLUMN_ANSWER) VALUES ('Which country is located in Asia?'                             , 'India'                   , 'USA'             , 'UK'                  , 'None'                , 'India'                   )",
            "INSERT INTO $TABLE_NAME ($COLUMN_QUESTION, $COLUMN_OPTION1, $COLUMN_OPTION2, $COLUMN_OPTION3, $COLUMN_OPTION4, $COLUMN_ANSWER) VALUES ('Which language(s) is/are used for Android app development?'    , 'Java'                    , 'Java & Kotlin'   , 'Kotlin'              , 'Swift'               , 'Java & Kotlin'           )",
            "INSERT INTO $TABLE_NAME ($COLUMN_QUESTION, $COLUMN_OPTION1, $COLUMN_OPTION2, $COLUMN_OPTION3, $COLUMN_OPTION4, $COLUMN_ANSWER) VALUES ('What is the largest ocean on Earth?'                           , 'Atlantic Ocean'          , 'Indian Ocean'    , 'Arctic Ocean'        , 'Pacific Ocean'       , 'Pacific Ocean'           )",
            "INSERT INTO $TABLE_NAME ($COLUMN_QUESTION, $COLUMN_OPTION1, $COLUMN_OPTION2, $COLUMN_OPTION3, $COLUMN_OPTION4, $COLUMN_ANSWER) VALUES ('Who wrote the play Hamlet?'                                  , 'William Shakespeare'     , 'Charles Dickens' , 'Jane Austen'         , 'F. Scott Fitzgerald' , 'William Shakespeare'     )",
            "INSERT INTO $TABLE_NAME ($COLUMN_QUESTION, $COLUMN_OPTION1, $COLUMN_OPTION2, $COLUMN_OPTION3, $COLUMN_OPTION4, $COLUMN_ANSWER) VALUES ('What is the chemical symbol for water?'                        , 'O'                       , 'H2O'             , 'H'                   , 'W'                   , 'H2O'                     )",
            "INSERT INTO $TABLE_NAME ($COLUMN_QUESTION, $COLUMN_OPTION1, $COLUMN_OPTION2, $COLUMN_OPTION3, $COLUMN_OPTION4, $COLUMN_ANSWER) VALUES ('Which planet is known as the Red Planet?'                      , 'Mars'                    , 'Jupiter'         , 'Saturn'              , 'Mercury'             , 'Mars'                    )",
            "INSERT INTO $TABLE_NAME ($COLUMN_QUESTION, $COLUMN_OPTION1, $COLUMN_OPTION2, $COLUMN_OPTION3, $COLUMN_OPTION4, $COLUMN_ANSWER) VALUES ('Who painted the Mona Lisa?'                                    , 'Vincent van Gogh'        , 'Pablo Picasso'   , 'Leonardo da Vinci'   , 'Claude Monet'        , 'Leonardo da Vinci'       )",
            "INSERT INTO $TABLE_NAME ($COLUMN_QUESTION, $COLUMN_OPTION1, $COLUMN_OPTION2, $COLUMN_OPTION3, $COLUMN_OPTION4, $COLUMN_ANSWER) VALUES ('Which continent is the least populated?'                       , 'Asia'                    , 'Africa'          , 'Australia'           , 'Antarctica'          , 'Antarctica'              )",
            "INSERT INTO $TABLE_NAME ($COLUMN_QUESTION, $COLUMN_OPTION1, $COLUMN_OPTION2, $COLUMN_OPTION3, $COLUMN_OPTION4, $COLUMN_ANSWER) VALUES ('Who invented the telephone?'                                   , 'Alexander Graham Bell'   , 'Thomas Edison'   , 'Nikola Tesla'        , 'Albert Einstein'     , 'Alexander Graham Bell'   )",
            "INSERT INTO $TABLE_NAME ($COLUMN_QUESTION, $COLUMN_OPTION1, $COLUMN_OPTION2, $COLUMN_OPTION3, $COLUMN_OPTION4, $COLUMN_ANSWER) VALUES ('Which city hosted the 2016 Summer Olympics?'                   , 'Tokyo'                   , 'Rio de Janeiro'  , 'London'              , 'Beijing'             , 'Rio de Janeiro'          )",
            "INSERT INTO $TABLE_NAME ($COLUMN_QUESTION, $COLUMN_OPTION1, $COLUMN_OPTION2, $COLUMN_OPTION3, $COLUMN_OPTION4, $COLUMN_ANSWER) VALUES ('What is the currency of Japan?'                                , 'Yen'                     , 'Dollar'          , 'Euro'                , 'Pound'               , 'Yen'                     )",
            "INSERT INTO $TABLE_NAME ($COLUMN_QUESTION, $COLUMN_OPTION1, $COLUMN_OPTION2, $COLUMN_OPTION3, $COLUMN_OPTION4, $COLUMN_ANSWER) VALUES ('Who discovered penicillin?'                                    , 'Alexander Fleming'       , 'Marie Curie'     , 'Louis Pasteur'       , 'Isaac Newton'        , 'Alexander Fleming'       )",
            "INSERT INTO $TABLE_NAME ($COLUMN_QUESTION, $COLUMN_OPTION1, $COLUMN_OPTION2, $COLUMN_OPTION3, $COLUMN_OPTION4, $COLUMN_ANSWER) VALUES ('What is the capital of Australia?'                              , 'Sydney'          , 'Melbourne'       , 'Canberra'        , 'Perth'       , 'Canberra'        )",
            "INSERT INTO $TABLE_NAME ($COLUMN_QUESTION, $COLUMN_OPTION1, $COLUMN_OPTION2, $COLUMN_OPTION3, $COLUMN_OPTION4, $COLUMN_ANSWER) VALUES ('Who wrote The Adventures of Sherlock Holmes?'                 , 'Arthur Conan Doyle', 'Agatha Christie' , 'Charles Dickens' , 'J.K. Rowling' , 'Arthur Conan Doyle' )",
            "INSERT INTO $TABLE_NAME ($COLUMN_QUESTION, $COLUMN_OPTION1, $COLUMN_OPTION2, $COLUMN_OPTION3, $COLUMN_OPTION4, $COLUMN_ANSWER) VALUES ('Which country hosted the FIFA World Cup in 2018?'               , 'Brazil'          , 'Russia'          , 'France'          , 'Germany'     , 'Russia'           )",
            "INSERT INTO $TABLE_NAME ($COLUMN_QUESTION, $COLUMN_OPTION1, $COLUMN_OPTION2, $COLUMN_OPTION3, $COLUMN_OPTION4, $COLUMN_ANSWER) VALUES ('How many continents are there?'                                 , '5'               , '6'               , '7'               , '8'           , '7'                )",
            "INSERT INTO $TABLE_NAME ($COLUMN_QUESTION, $COLUMN_OPTION1, $COLUMN_OPTION2, $COLUMN_OPTION3, $COLUMN_OPTION4, $COLUMN_ANSWER) VALUES ('Who is known as the Father of Computers?'                     , 'Charles Babbage' , 'Alan Turing'     , 'Steve Jobs'      , 'Bill Gates'  , 'Charles Babbage'  )",
            "INSERT INTO $TABLE_NAME ($COLUMN_QUESTION, $COLUMN_OPTION1, $COLUMN_OPTION2, $COLUMN_OPTION3, $COLUMN_OPTION4, $COLUMN_ANSWER) VALUES ('Which city is known as the City of Love?'                     , 'Venice'          , 'Paris'           , 'Rome'            , 'Barcelona'   , 'Paris'            )",
            "INSERT INTO $TABLE_NAME ($COLUMN_QUESTION, $COLUMN_OPTION1, $COLUMN_OPTION2, $COLUMN_OPTION3, $COLUMN_OPTION4, $COLUMN_ANSWER) VALUES ('Who painted the ceiling of the Sistine Chapel?'                 , 'Raphael'         , 'Leonardo da Vinci', 'Michelangelo'    , 'Donatello'   , 'Michelangelo'     )",
            "INSERT INTO $TABLE_NAME ($COLUMN_QUESTION, $COLUMN_OPTION1, $COLUMN_OPTION2, $COLUMN_OPTION3, $COLUMN_OPTION4, $COLUMN_ANSWER) VALUES ('What is the largest mammal?'                                    , 'Elephant'        , 'Blue Whale'      , 'Giraffe'         , 'Hippopotamus', 'Blue Whale'       )",
            "INSERT INTO $TABLE_NAME ($COLUMN_QUESTION, $COLUMN_OPTION1, $COLUMN_OPTION2, $COLUMN_OPTION3, $COLUMN_OPTION4, $COLUMN_ANSWER) VALUES ('Which is the longest river in the world?'                       , 'Amazon'          , 'Nile'            , 'Mississippi'     , 'Yangtze'     , 'Nile'             )",
            "INSERT INTO $TABLE_NAME ($COLUMN_QUESTION, $COLUMN_OPTION1, $COLUMN_OPTION2, $COLUMN_OPTION3, $COLUMN_OPTION4, $COLUMN_ANSWER) VALUES ('Who wrote the novel 1984?'                                    , 'Aldous Huxley'   , 'George Orwell'   , 'F. Scott Fitzgerald', 'J.R.R. Tolkien', 'George Orwell'    )",
            "INSERT INTO $TABLE_NAME ($COLUMN_QUESTION, $COLUMN_OPTION1, $COLUMN_OPTION2, $COLUMN_OPTION3, $COLUMN_OPTION4, $COLUMN_ANSWER) VALUES ('Which planet is known as the Morning Star?'                   , 'Mars'            , 'Venus'           , 'Jupiter'         , 'Mercury'     , 'Venus'            )",
            "INSERT INTO $TABLE_NAME ($COLUMN_QUESTION, $COLUMN_OPTION1, $COLUMN_OPTION2, $COLUMN_OPTION3, $COLUMN_OPTION4, $COLUMN_ANSWER) VALUES ('In which year did the Titanic sink?'                            , '1912'            , '1908'            , '1921'            , '1899'        , '1912'             )",
            "INSERT INTO $TABLE_NAME ($COLUMN_QUESTION, $COLUMN_OPTION1, $COLUMN_OPTION2, $COLUMN_OPTION3, $COLUMN_OPTION4, $COLUMN_ANSWER) VALUES ('Who wrote Pride and Prejudice?'                               , 'Jane Austen'     , 'Charlotte Bronte', 'Emily Dickinson' , 'Leo Tolstoy' , 'Jane Austen'      )",
            "INSERT INTO $TABLE_NAME ($COLUMN_QUESTION, $COLUMN_OPTION1, $COLUMN_OPTION2, $COLUMN_OPTION3, $COLUMN_OPTION4, $COLUMN_ANSWER) VALUES ('What is the chemical symbol for gold?'                           , 'Gd'              , 'Au'              , 'Ag'              , 'Gl'          , 'Au'               )",
            "INSERT INTO $TABLE_NAME ($COLUMN_QUESTION, $COLUMN_OPTION1, $COLUMN_OPTION2, $COLUMN_OPTION3, $COLUMN_OPTION4, $COLUMN_ANSWER) VALUES ('Which country is known as the Land of the Rising Sun?'           , 'China'           , 'Japan'           , 'Vietnam'         , 'South Korea' , 'Japan'            )",
            "INSERT INTO $TABLE_NAME ($COLUMN_QUESTION, $COLUMN_OPTION1, $COLUMN_OPTION2, $COLUMN_OPTION3, $COLUMN_OPTION4, $COLUMN_ANSWER) VALUES ('Who discovered America?'                                        , 'Christopher Columbus', 'Marco Polo'      , 'Vasco da Gama'   , 'Amerigo Vespucci', 'Christopher Columbus' )",
            "INSERT INTO $TABLE_NAME ($COLUMN_QUESTION, $COLUMN_OPTION1, $COLUMN_OPTION2, $COLUMN_OPTION3, $COLUMN_OPTION4, $COLUMN_ANSWER) VALUES ('What is the largest desert in the world?'                       , 'Sahara Desert'    , 'Arabian Desert'  , 'Gobi Desert'     , 'Kalahari Desert' , 'Sahara Desert'        )",
            "INSERT INTO $TABLE_NAME ($COLUMN_QUESTION, $COLUMN_OPTION1, $COLUMN_OPTION2, $COLUMN_OPTION3, $COLUMN_OPTION4, $COLUMN_ANSWER) VALUES ('Who painted the Starry Night?'                                , 'Vincent van Gogh' , 'Pablo Picasso'   , 'Leonardo da Vinci', 'Claude Monet'    , 'Vincent van Gogh'     )",
            "INSERT INTO $TABLE_NAME ($COLUMN_QUESTION, $COLUMN_OPTION1, $COLUMN_OPTION2, $COLUMN_OPTION3, $COLUMN_OPTION4, $COLUMN_ANSWER) VALUES ('Which country is known as the Land of Fire and Ice?'             , 'Greenland'        , 'Iceland'         , 'Norway'          , 'Finland'         , 'Iceland'              )",
            "INSERT INTO $TABLE_NAME ($COLUMN_QUESTION, $COLUMN_OPTION1, $COLUMN_OPTION2, $COLUMN_OPTION3, $COLUMN_OPTION4, $COLUMN_ANSWER) VALUES ('How many bones are there in the adult human body?'               , '206'              , '200'             , '210'             , '220'             , '206'                  )",
            "INSERT INTO $TABLE_NAME ($COLUMN_QUESTION, $COLUMN_OPTION1, $COLUMN_OPTION2, $COLUMN_OPTION3, $COLUMN_OPTION4, $COLUMN_ANSWER) VALUES ('Who wrote the play Romeo and Juliet?'                         , 'William Shakespeare', 'Jane Austen'     , 'Charles Dickens' , 'Mark Twain'      , 'William Shakespeare' )",
            "INSERT INTO $TABLE_NAME ($COLUMN_QUESTION, $COLUMN_OPTION1, $COLUMN_OPTION2, $COLUMN_OPTION3, $COLUMN_OPTION4, $COLUMN_ANSWER) VALUES ('Who invented the light bulb?'                                   , 'Thomas Edison'    , 'Alexander Graham Bell', 'Nikola Tesla'    , 'Albert Einstein' , 'Thomas Edison'        )",
            "INSERT INTO $TABLE_NAME ($COLUMN_QUESTION, $COLUMN_OPTION1, $COLUMN_OPTION2, $COLUMN_OPTION3, $COLUMN_OPTION4, $COLUMN_ANSWER) VALUES ('Which city hosted the 2012 Summer Olympics?'                     , 'London'           , 'Beijing'         , 'Sydney'          , 'Athens'          , 'London'               )",
            "INSERT INTO $TABLE_NAME ($COLUMN_QUESTION, $COLUMN_OPTION1, $COLUMN_OPTION2, $COLUMN_OPTION3, $COLUMN_OPTION4, $COLUMN_ANSWER) VALUES ('How many planets are there in the solar system?'                 , '8'                , '9'               , '10'              , '7'               , '8'                    )",
            "INSERT INTO $TABLE_NAME ($COLUMN_QUESTION, $COLUMN_OPTION1, $COLUMN_OPTION2, $COLUMN_OPTION3, $COLUMN_OPTION4, $COLUMN_ANSWER) VALUES ('Who is the author of the Harry Potter series?'                   , 'J.K. Rowling'     , 'Stephen King'    , 'George R.R. Martin', 'J.R.R. Tolkien'  , 'J.K. Rowling'        )",
            "INSERT INTO $TABLE_NAME ($COLUMN_QUESTION, $COLUMN_OPTION1, $COLUMN_OPTION2, $COLUMN_OPTION3, $COLUMN_OPTION4, $COLUMN_ANSWER) VALUES ('What is the chemical symbol for sodium?'                         , 'S'                , 'Na'              , 'So'              , 'N'               , 'Na'                   )",
            "INSERT INTO $TABLE_NAME ($COLUMN_QUESTION, $COLUMN_OPTION1, $COLUMN_OPTION2, $COLUMN_OPTION3, $COLUMN_OPTION4, $COLUMN_ANSWER) VALUES ('Which river flows through Egypt?'                                , 'Nile'             , 'Amazon'          , 'Yangtze'         , 'Mississippi'     , 'Nile'                 )",
            "INSERT INTO $TABLE_NAME ($COLUMN_QUESTION, $COLUMN_OPTION1, $COLUMN_OPTION2, $COLUMN_OPTION3, $COLUMN_OPTION4, $COLUMN_ANSWER) VALUES ('Who painted the Mona Lisa?'                                   , 'Leonardo da Vinci' , 'Vincent van Gogh', 'Pablo Picasso'   , 'Claude Monet'    , 'Leonardo da Vinci'   )",
            "INSERT INTO $TABLE_NAME ($COLUMN_QUESTION, $COLUMN_OPTION1, $COLUMN_OPTION2, $COLUMN_OPTION3, $COLUMN_OPTION4, $COLUMN_ANSWER) VALUES ('What year did World War II end?'                                , '1945'             , '1939'            , '1941'            , '1943'            , '1945'                )",
            "INSERT INTO $TABLE_NAME ($COLUMN_QUESTION, $COLUMN_OPTION1, $COLUMN_OPTION2, $COLUMN_OPTION3, $COLUMN_OPTION4, $COLUMN_ANSWER) VALUES ('Which country is known as the Land of the Rising Sun?'           , 'Japan'            , 'China'           , 'Korea'           , 'Vietnam'         , 'Japan'               )",
            "INSERT INTO $TABLE_NAME ($COLUMN_QUESTION, $COLUMN_OPTION1, $COLUMN_OPTION2, $COLUMN_OPTION3, $COLUMN_OPTION4, $COLUMN_ANSWER) VALUES ('What is the largest planet in our solar system?'                 , 'Jupiter'          , 'Saturn'          , 'Neptune'         , 'Uranus'          , 'Jupiter'             )",
            "INSERT INTO $TABLE_NAME ($COLUMN_QUESTION, $COLUMN_OPTION1, $COLUMN_OPTION2, $COLUMN_OPTION3, $COLUMN_OPTION4, $COLUMN_ANSWER) VALUES ('Who wrote To Kill a Mockingbird?'                             , 'Harper Lee'       , 'Mark Twain'      , 'F. Scott Fitzgerald', 'J.D. Salinger'  , 'Harper Lee'          )",
            "INSERT INTO $TABLE_NAME ($COLUMN_QUESTION, $COLUMN_OPTION1, $COLUMN_OPTION2, $COLUMN_OPTION3, $COLUMN_OPTION4, $COLUMN_ANSWER) VALUES ('Which planet is known as the Red Planet?'                       , 'Mars'             , 'Venus'           , 'Jupiter'         , 'Mercury'         , 'Mars'                )",
            "INSERT INTO $TABLE_NAME ($COLUMN_QUESTION, $COLUMN_OPTION1, $COLUMN_OPTION2, $COLUMN_OPTION3, $COLUMN_OPTION4, $COLUMN_ANSWER) VALUES ('How many bones are there in the human body?'                     , '206'              , '208'            , '210'             , '212'             , '206'                 )",
            "INSERT INTO $TABLE_NAME ($COLUMN_QUESTION, $COLUMN_OPTION1, $COLUMN_OPTION2, $COLUMN_OPTION3, $COLUMN_OPTION4, $COLUMN_ANSWER) VALUES ('Who discovered penicillin?'                                    , 'Alexander Fleming', 'Marie Curie'     , 'Louis Pasteur'   , 'Isaac Newton'    , 'Alexander Fleming'  )",
            "INSERT INTO $TABLE_NAME ($COLUMN_QUESTION, $COLUMN_OPTION1, $COLUMN_OPTION2, $COLUMN_OPTION3, $COLUMN_OPTION4, $COLUMN_ANSWER) VALUES ('Which is the longest river in the world?'                       , 'Nile'             , 'Amazon'          , 'Mississippi'     , 'Yangtze'         , 'Nile'                )",
            "INSERT INTO $TABLE_NAME ($COLUMN_QUESTION, $COLUMN_OPTION1, $COLUMN_OPTION2, $COLUMN_OPTION3, $COLUMN_OPTION4, $COLUMN_ANSWER) VALUES ('What is the currency of Japan?'                                 , 'Yen'              , 'Dollar'          , 'Euro'            , 'Pound'           , 'Yen'                 )",
            "INSERT INTO $TABLE_NAME ($COLUMN_QUESTION, $COLUMN_OPTION1, $COLUMN_OPTION2, $COLUMN_OPTION3, $COLUMN_OPTION4, $COLUMN_ANSWER) VALUES ('Who wrote The Catcher in the Rye?'                            , 'J.D. Salinger'    , 'Harper Lee'      , 'F. Scott Fitzgerald', 'Mark Twain'     , 'J.D. Salinger'       )",
            "INSERT INTO $TABLE_NAME ($COLUMN_QUESTION, $COLUMN_OPTION1, $COLUMN_OPTION2, $COLUMN_OPTION3, $COLUMN_OPTION4, $COLUMN_ANSWER) VALUES ('What is the chemical symbol for iron?'                           , 'Fe'               , 'Ir'              , 'In'              , 'Io'              , 'Fe'                  )",
            "INSERT INTO $TABLE_NAME ($COLUMN_QUESTION, $COLUMN_OPTION1, $COLUMN_OPTION2, $COLUMN_OPTION3, $COLUMN_OPTION4, $COLUMN_ANSWER) VALUES ('Which city is known as the City of Love?'                        , 'Paris'            , 'Venice'          , 'Rome'            , 'Barcelona'       , 'Paris'               )",
            "INSERT INTO $TABLE_NAME ($COLUMN_QUESTION, $COLUMN_OPTION1, $COLUMN_OPTION2, $COLUMN_OPTION3, $COLUMN_OPTION4, $COLUMN_ANSWER) VALUES ('In which year did the French Revolution begin?'                 , '1789'            , '1776'            , '1804'            , '1812'            , '1789'                )",
            "INSERT INTO $TABLE_NAME ($COLUMN_QUESTION, $COLUMN_OPTION1, $COLUMN_OPTION2, $COLUMN_OPTION3, $COLUMN_OPTION4, $COLUMN_ANSWER) VALUES ('Who was the first President of the United States?'              , 'George Washington', 'Thomas Jefferson', 'Abraham Lincoln' , 'John Adams'      , 'George Washington'   )",
            "INSERT INTO $TABLE_NAME ($COLUMN_QUESTION, $COLUMN_OPTION1, $COLUMN_OPTION2, $COLUMN_OPTION3, $COLUMN_OPTION4, $COLUMN_ANSWER) VALUES ('Which battle is considered the turning point in the American Civil War?' , 'Battle of Gettysburg' , 'Battle of Antietam', 'Battle of Vicksburg', 'Battle of Bull Run', 'Battle of Gettysburg' )",
            "INSERT INTO $TABLE_NAME ($COLUMN_QUESTION, $COLUMN_OPTION1, $COLUMN_OPTION2, $COLUMN_OPTION3, $COLUMN_OPTION4, $COLUMN_ANSWER) VALUES ('Who wrote the Communist Manifesto?'                           , 'Karl Marx'       , 'Friedrich Engels', 'Vladimir Lenin'  , 'Joseph Stalin'   , 'Karl Marx'           )",
            "INSERT INTO $TABLE_NAME ($COLUMN_QUESTION, $COLUMN_OPTION1, $COLUMN_OPTION2, $COLUMN_OPTION3, $COLUMN_OPTION4, $COLUMN_ANSWER) VALUES ('Which civilization built the Great Pyramids of Giza?'            , 'Ancient Egyptians', 'Ancient Greeks'  , 'Mesopotamians'   , 'Mayans'          , 'Ancient Egyptians'   )",
            "INSERT INTO $TABLE_NAME ($COLUMN_QUESTION, $COLUMN_OPTION1, $COLUMN_OPTION2, $COLUMN_OPTION3, $COLUMN_OPTION4, $COLUMN_ANSWER) VALUES ('When did World War I begin?'                                    , '1914'            , '1917'            , '1919'            , '1912'            , '1914'                )",
            "INSERT INTO $TABLE_NAME ($COLUMN_QUESTION, $COLUMN_OPTION1, $COLUMN_OPTION2, $COLUMN_OPTION3, $COLUMN_OPTION4, $COLUMN_ANSWER) VALUES ('Who was the first emperor of China?'                            , 'Qin Shi Huang'   , 'Genghis Khan'    , 'Emperor Han'     , 'Mao Zedong'      , 'Qin Shi Huang'       )",
            "INSERT INTO $TABLE_NAME ($COLUMN_QUESTION, $COLUMN_OPTION1, $COLUMN_OPTION2, $COLUMN_OPTION3, $COLUMN_OPTION4, $COLUMN_ANSWER) VALUES ('Which famous speech began with Four score and seven years ago?' , 'Gettysburg Address' , 'I Have a Dream'  , 'We Shall Overcome', 'Emancipation Proclamation', 'Gettysburg Address' )",
            "INSERT INTO $TABLE_NAME ($COLUMN_QUESTION, $COLUMN_OPTION1, $COLUMN_OPTION2, $COLUMN_OPTION3, $COLUMN_OPTION4, $COLUMN_ANSWER) VALUES ('Who was the first woman to fly solo across the Atlantic Ocean?'  , 'Amelia Earhart'  , 'Sally Ride'      , 'Jacqueline Cochran', 'Bessie Coleman'  , 'Amelia Earhart'      )",
            "INSERT INTO $TABLE_NAME ($COLUMN_QUESTION, $COLUMN_OPTION1, $COLUMN_OPTION2, $COLUMN_OPTION3, $COLUMN_OPTION4, $COLUMN_ANSWER) VALUES ('During which war was the Battle of Waterloo fought?'             , 'Napoleonic Wars' , 'American Civil War', 'World War I'      , 'World War II'    , 'Napoleonic Wars'     )",
            "INSERT INTO $TABLE_NAME ($COLUMN_QUESTION, $COLUMN_OPTION1, $COLUMN_OPTION2, $COLUMN_OPTION3, $COLUMN_OPTION4, $COLUMN_ANSWER) VALUES ('Who was the longest-reigning monarch in British history?'        , 'Queen Victoria'  , 'Queen Elizabeth II', 'King George III'  , 'King Henry VIII' , 'Queen Elizabeth II'  )",
        )
        for (question in questions) {
            db.execSQL(question)
        }
    }
}